@startuml

!theme plain
left to right direction
skinparam linetype ortho

class AbstractAuditable {
   createdDate:  Date 
   lastModifiedDate:  Date 
}
class AbstractPersistable {
   id:  PK 
}
class AuditableEntity {
   creadoEn:  Instant 
   creadoPor:  UUID 
   modificadoEn:  Instant 
   modificadoPor:  UUID 
}
class ExcepcionDisponibilidad {
   id:  UUID 
   cerrado:  boolean 
   fecha:  LocalDate 
   finMin:  Integer 
   inicioMin:  Integer 
   vetId:  UUID 
}
class Mascota {
   id:  UUID 
   especie:  Especie 
   fechaNacimiento:  LocalDate 
   nombre:  String 
   pesoKg:  Double 
   raza:  String 
   sexo:  String 
   tutorId:  UUID 
}
class Oferta {
   id:  UUID 
   activo:  boolean 
   duracionMin:  int 
   precioCents:  int 
   vetId:  UUID 
}
class Procedimiento {
   id:  UUID 
   categoria:  String 
   nombre:  String 
}
class ReglaSemanal {
   id:  UUID 
   dia:  int 
   finMin:  int 
   inicioMin:  int 
   vetId:  UUID 
}
class Reserva {
   id:  UUID 
   estado:  EstadoReserva 
   inicio:  Instant 
   mascotaId:  UUID 
   nota:  String 
   ofertaId:  UUID 
   tutorId:  UUID 
}
class Rol {
   id:  Long 
   nombre:  String 
}
class Usuario {
   id:  UUID 
   email:  String 
   fotoUrl:  String 
   nombre:  String 
}
class VistaOfertaEntity {
   ofertaId:  UUID 
   conStock:  boolean 
   nombre:  String 
   precioCents:  int 
   procedimientoId:  UUID 
}
class VistaVetEntity {
   vetId:  UUID 
   bucket:  String 
   lat:  double 
   lon:  double 
   nombre:  String 
   openNow:  boolean 
}

AbstractAuditable        -[#595959,plain]-^  AbstractPersistable     
ExcepcionDisponibilidad  -[#595959,plain]-^  AuditableEntity         
Mascota                  -[#595959,plain]-^  AuditableEntity         
Oferta                   -[#595959,plain]-^  AuditableEntity         
Oferta                  "0..*" -[#595959,plain]-> "0..1" Procedimiento           
Procedimiento            -[#595959,plain]-^  AuditableEntity         
ReglaSemanal             -[#595959,plain]-^  AuditableEntity         
Reserva                  -[#595959,plain]-^  AuditableEntity         
Usuario                 "0..*" -[#595959,plain]-> "0..*" Rol                     
VistaVetEntity          "1" <-[#595959,plain]-> "1..*" VistaOfertaEntity       
@enduml
